version: '3.8'

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432


  user_app:
    build: 
      network: host
      context: ./
      dockerfile: Dockerfile
      depends_on:
        postgres:
          condition: service_completed_successfully
  

    environment:
      - DATABSE_URL=postgresql://postgres:mysecretpassword@postgres:5432/postgres

    ports:
      - 3000:3000